### ISSUE TITLE
Hi, thanks for sharing this through github, i have a question

### ISSUE THREAD

**Issue by kailuowang** [smartbitcoin/dqn#1]
Did you guys experience a significant speed drop after 50000 steps. The speed dropped from 200 steps/sec to 6-7 steps right after 50,000 steps. It's consistently happening on two machines I have. 
Any advice will be really appreciated! Thanks!

**Comment by smartbitcoin** [comment]
not at all. I only saw it slow down when I run on gpu and gpu ram almost run out.

**Comment by kailuowang** [comment]
Thanks very much. Another github user noticed the same slow down as me. https://github.com/whackashoe/Human_Level_Control_through_Deep_Reinforcement_Learning
May I ask which OS did you run it on?

**Comment by kailuowang** [comment]
mystery solved: user stupidity
